### PR TITLE
more CI

### PR DESCRIPTION
**Pull request by ArnoStrouwen**

### CODE REVIEW

**Comment by ArnoStrouwen** [comment]
SciML is moving to throwing errors on hitting deprecation in CI.

I have no idea where the deprecation warning for Catalyst.@register is coming from. The Catalyst version the CI is using does not seem to still use Catalyst.@register? @TorkelE do you have any idea?

**Comment by ChrisRackauckas** [comment]
It should be `@symbolic_register`

**Comment by ArnoStrouwen** [comment]
In Catalyst, everything seems to be the other way around: `@register_symbolic`.

**Comment by isaacsas** [comment]
I can’t find anywhere that `@register` is being used in Catalyst, here, or MTK. Maybe this is some aqua-related issue? I was finding it was giving what seemed like spurious ambiguities at times. Maybe it would be easier to first get these CI additions working with MTK and then Catalyst before here so we can know there aren't issues with lower-level dependencies?

**Comment by ChrisRackauckas** [comment]
A search isn't finding any https://github.com/search?q=org%3ASciML+register&type=code&p=1. Odd.

**Comment by ArnoStrouwen** [comment]
This should be good to go  now.

**Pull request merged**
